#!/bin/bash

SERIAL_PATH="/dev/ttyUSB0"
SERIAL_BAUD=9600
COMMAND=""
CLI_NAME="ardmon"
SERIAL_OUTPUT="/dev/null"

usage() {
    echo "Usage:"
    echo "  $CLI_NAME start (-p [path] -b [baud] -o [output])       - Start background serial connection"
    echo "  $CLI_NAME stop                                          - Stop background connection"
    echo "  $CLI_NAME send [command 1, command 2...]                - Send command to Arduino"
}

# openSerial() {
    
# }

start() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -p)
                SERIAL_PATH=$2
                shift 2
                ;;
            -b)
                SERIAL_BAUD=$2
                shift 2
                ;;
            -o)
                SERIAL_OUTPUT=$2
                shift 2
                ;;
            *)
                echo "Invalid usage: use '$CLI_NAME help' to get usage"
                exit 1
                ;;
        esac
    done

    echo "start at $SERIAL_PATH and $SERIAL_BAUD"
    openSerial $SERIAL_PATH $SERIAL_BAUD
}

# main entry
if [[ $# -gt 0 ]]; then

    # get command and remove argument
    COMMAND=$1
    shift 1

    case "$COMMAND" in
        start)
            start $@ # pass remaining arguments to function
            exit 0
            ;;
        help)
            usage
            exit 0
            ;;
        *)
            echo "Use '$CLI_NAME help' to get usage"
            exit 1
            ;;
    esac
else
    echo "Use '$CLI_NAME help' to get usage"
    exit 1
fi


